CREATE TABLE "InsuranceProvision" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "clinicId" TEXT NOT NULL,
    "patientId" TEXT NOT NULL,
    "treatmentCaseId" TEXT,
    "insuranceProviderName" TEXT NOT NULL,
    "insuranceType" TEXT NOT NULL,
    "policyNumber" TEXT,
    "provisionNumber" TEXT,
    "status" TEXT NOT NULL DEFAULT 'draft',
    "requestedAmount" REAL NOT NULL,
    "approvedAmount" REAL,
    "patientResponsibilityAmount" REAL,
    "currency" TEXT NOT NULL DEFAULT 'TRY',
    "submittedAt" DATETIME,
    "respondedAt" DATETIME,
    "rejectionReason" TEXT,
    "notes" TEXT,
    "assignedToId" TEXT,
    "createdById" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "InsuranceProvision_clinicId_fkey" FOREIGN KEY ("clinicId") REFERENCES "Clinic" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "InsuranceProvision_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "InsuranceProvision_treatmentCaseId_fkey" FOREIGN KEY ("treatmentCaseId") REFERENCES "TreatmentCase" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "InsuranceProvision_assignedToId_fkey" FOREIGN KEY ("assignedToId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "InsuranceProvision_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

ALTER TABLE "ActivityLog" ADD COLUMN "insuranceProvisionId" TEXT;
